# Generated by Django 2.2.4 on 2022-09-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dojo_Ninjas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ninja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='dojo',
            old_name='city',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='dojo',
            old_name='name',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='dojo',
            name='state',
        ),
    ]
