# Generated by Django 2.2.4 on 2022-09-26 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dojo_Ninjas', '0002_auto_20220926_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='ninja',
            name='dojo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ninjas', to='Dojo_Ninjas.dojo'),
            preserve_default=False,
        ),
    ]
