# Generated by Django 2.2.4 on 2022-09-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dojos_Ninjas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ninja',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='ninja',
            name='last_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
